#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Retrieve manifest arguments
app=$YNH_APP_INSTANCE_NAME
domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
readonly app_system_name=$YNH_APP_ARG_SYSTEM_NAME
readonly app_display_name=$YNH_APP_ARG_DISPLAY_NAME
readonly is_public=$YNH_APP_ARG_IS_PUBLIC

readonly final_path=/var/www/$app_system_name

ynh_script_progression --message="Configuring app settings..." --weight=1
ynh_webpath_register $app $domain $path
ynh_app_setting_set "$app" display_name "$app_display_name"
ynh_app_setting_set "$app" system_name "$app_system_name"
ynh_app_setting_set "$app" is_public "$is_public"

ynh_script_progression --message="Installing dependencies..." --weight=1
ynh_install_app_dependencies virtualenv \
                             python3-dev \
                             python3-virtualenv \
                             python3-pip                           

ynh_script_progression --message="Initialize Python venv..." --weight=1
mkdir -p $final_path
pushd $final_path
virtualenv -p python3 venv
set +o nounset 
source venv/bin/activate
set -o nounset 
pip install -U pip
pip install Flask
pip install Flask-Script
pip install gunicorn
popd

ynh_script_progression --message="Configuring Flask app..." --weight=1
# Copy hello-world sources
cp -r ../sources/* $final_path/

# App settings
ynh_replace_string "__YNH_APP_WEBPATH__" "$path"       ../conf/settings.py
ynh_replace_string "__YNH_APP_FSPATH__"  "$final_path" ../conf/settings.py

cp ../conf/settings.py $final_path/app/settings_local.py

# Gunicorn
ynh_replace_string "__YNH_APP_NAME__" "$app_system_name" ../conf/gunicorn.py
ynh_replace_string "__YNH_APP_PATH__" "$final_path"      ../conf/gunicorn.py
cp ../conf/gunicorn.py $final_path/

# Set permissions
ynh_script_progression --message="Setting permissions..." --weight=1
useradd $app_system_name -d $final_path || echo "User already exists"
chown -R $app_system_name:www-data $final_path

# Log folder
ynh_script_progression --message="Creating log folder..." --weight=1
mkdir -p /var/log/$app_system_name
chown -R $app_system_name:www-data /var/log/$app_system_name

# Systemd config
ynh_replace_string "__YNH_APP_NAME__" "$app_system_name" ../conf/app.service
ynh_replace_string "__YNH_APP_PATH__" "$final_path"      ../conf/app.service
cp ../conf/app.service /etc/systemd/system/$app_system_name.service

ynh_script_progression --message="Reloading daemon..." --weight=1
systemctl daemon-reload
systemctl enable $app_system_name
yunohost service add $app_system_name -l /var/log/$app_system_name/access.log


# Nginx conf
ynh_script_progression --message="Configuring nginx and SSOwat..." --weight=1
ynh_replace_string "__YNH_APP_NAME__"    "$app_system_name" ../conf/nginx.conf
ynh_replace_string "__YNH_APP_WEBPATH__" "$path"            ../conf/nginx.conf
ynh_replace_string "__YNH_APP_FSPATH__"  "$final_path"      ../conf/nginx.conf
cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app_system_name.conf

# Reload Nginx and regenerate SSOwat conf
service nginx reload
yunohost app ssowatconf

ynh_script_progression --message="Starting app..." --weight=1
systemctl start $app_system_name

ynh_script_progression --message="Installation of $app completed" --last
